### PR TITLE
refactor to use JavaScript classes

### PR DESCRIPTION
**Pull request by momo-87**
- [ ] Creating Book object using classes
- [ ] Creating BookList Array using classes
- [ ] Refactoring all the functions (using classes)
- [ ] Adding styles

### CODE REVIEW

**Review by DammyShittu — APPROVED** [review]
Hi @momo-87 and @otmaneechchafyky,

## Highlights
✔️ Refactor to classes

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly edit your description to be more elaborate and describe what you did in this project

  image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by KDlamini — APPROVED** [review]
### Hi @momo-87 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the project requirements. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

## Highlights 🌟

✔️ Codebase is very clean and organized
✔️ Correct use classes and class methods are well-implemented
✔️ Kudos to using ES6 syntax properly

# Status: Approved ✔️ 



Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by V-Blaze — COMMENTED** [review]
Hi @momo-87  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

dcentl8-9b96e129-9725-401b-ac34-2feb990202a0

## Invalid Code Review Request

## You have submitted a project with a pull request that has already been approved. Please kindly merge the pull request if it has been approved by a code reviewer and then submit the project in your dashboard. :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by duskotmane** [comment]
@V-Blaze @KDlamini  Hi, actually I don't know why even the last reviewer approved our project but it still displayed as not finished and requires changes, any help, please?

**Comment by enniopo** [comment]
Hi @otmaneechchafyky, the project has been now approved. 
@V-Blaze thanks for escalating this.

**Pull request merged**
